#!/bin/bash

# Config data.
CMAKE_BUILD_TYPE=Release
CMAKE_CXX_FLAGS=""
CMAKE_CXX_COMPILER=/opt/toolchain/devel3/gcc-10.1.0/bin/g++
CMAKE_C_COMPILER=/opt/toolchain/devel3/gcc-10.1.0/bin/gcc
CMAKE_GENERATOR=Ninja
CMAKE_INSTALL_PREFIX=/usr/local
QT_QMAKE_EXECUTABLE=/usr/bin/qmake6
CMAKE_PREFIX_PATH=/usr

# Init cmake variables.
CMAKE_CONFIG="-DCMAKE_GENERATOR:STRING=${CMAKE_GENERATOR} -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE} -DQT_QMAKE_EXECUTABLE:FILEPATH=${QT_QMAKE_EXECUTABLE} -DCMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH} -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER} -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER} -DCMAKE_CXX_FLAGS_INIT:STRING=${CMAKE_CXX_FLAGS}"

# Init build dir.
BUILD_DIR=../out/${CMAKE_BUILD_TYPE}
cmake -B ${BUILD_DIR}  ${CMAKE_CONFIG}

# Build.
cmake --build ${BUILD_DIR} --target all

# Zip archieve.
cd ${BUILD_DIR}/..
zip -r ${CMAKE_BUILD_TYPE}.zip ${CMAKE_BUILD_TYPE}

# Test.
# qtcreator -pluginpath ${BUILD_DIR} &
